language: go

go:
    - 1.4.2
    - 1.5
    - tip

before_install:
  - wget http://archive.apache.org/dist/zookeeper/zookeeper-3.3.3/zookeeper-3.3.3.tar.gz
  - tar -zxvf zookeeper*tar.gz

before_script:
  - ln -s zookeeper-3.3.3.tar.gz loadbalancer/zk/
